### ISSUE TITLE
Descrever metodologia de gestão de projeto (Scrum)

### ISSUE THREAD

**Issue by calebefazzani** [Equipe-HYVE/petshow-backend#19]
Texto descritivo sobre o modelo que usaremos para a gestão do projeto (Scrum com ferramenta Kanbam) e sua utilização pela equipe (formato das sprints, etc).

**Comment by thiagoxra** [comment]
Backlog definition foi feita no dia 19/03, online (duração de 2 horas, participantes: todos); Sprint planning da primeira sprint foi feita no dia 19/03 também (definição do que seria feito apenas naquela semana) (junto com backlog definition); Sprint review / Sprint retrospective e Sprint planning da próxima sprint são feitos semanalmente, no último dia da sprint (2 horas de duração). Sprints de 1 semana.
