### ISSUE TITLE
Criar Colunas Novas - CÓDIGO + MER + DICIONÁRIO DE DADOS)

### ISSUE THREAD

**Issue by thiagoxra** [Equipe-HYVE/petshow-backend#208]
[CÓDIGO] Dentro das tabelas - indicar que foi feito a solicitação de cadastor mas ainda não foi liberada! faltou validação. Revezamento temporal - como alguem solicita o cadastro? Alguem cadastrou e o estado está diferente? Alguma flag que não esteja clara. -> Ação: adicionar colunas em todas as tabelas (MER + DICIONÁRIO DE DADOS): data de criação, data de alteração, usuário que criou, flag de status (se o cadastro já foi ativado através do e-mail enviado para a pessoa)

[CÓDIGO] Usando clear: mysql - não suporta geolocalização. Falta campo geo-espacial. Eu quero saber quem está proximo de mim e minha localização é X. tem que te rum dado geoespacial dentro do banco na hora do cadastro, usando o google, guarda a geolocalização no banco. -> Ação: adicionar campo de Geoloc na tabela Conta (MER + DICIONÁRIO DE DADOS)

[CÓDIGO] Incluir na tabela do banco as notas agregadas (calculadas). Grande volume pode atrapalhar no calculo na hora. -> AÇÃO: Adicionar coluna de média nas tabelas de agendamento, serviço e conta (MER + DICIONÁRIO DE DADOS) - Queileb

**Comment by nathaliafischer** [comment]
Guilherme faz MER, Thiago faz dicionario de dados
