### ISSUE TITLE
Funcionalidade de envio de e-mail no momento do cadastro

### ISSUE THREAD

**Issue by nathaliafischer** [Equipe-HYVE/petshow-backend#215]

**Comment by calebefazzani** [comment]
Tentei colocar o SendGrid no heroku só q fiz besteira aí tive q tirar e depois q tirei não deixou. Posso tentar entrar em contato com o suporte técnico pra arrumar o problema. De qualquer forma, o email está sendo enviado com email q criei no gmail para testar.
